# storage/minio-credentials-for-cnpg.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: minio-credentials
  namespace: storage

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: minio-credentials

  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: storage/minio
        property: access_key

    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: storage/minio
        property: password
